# --- ETAPA 1: BUILD (Compilación) ---
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . . 
RUN npm run build

# --- ETAPA 2: NGINX (Servidor Web) --- el mas usado e implementado
FROM nginx:alpine
# copiamos la carpeta /dist compilada a la carpeta de Nginx
COPY --from=builder /app/dist /usr/share/nginx/html
# exponemos el puerto 80
EXPOSE 80
# arrancamos Nginx
CMD ["nginx", "-g", "daemon off;"]